apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: trading-bot

resources:
  - prometheus-config.yaml
  - prometheus-deployment.yaml
  - grafana-config.yaml
  - grafana-deployment.yaml

commonLabels:
  component: monitoring
  project: trading-bot

